apt install net-tools -y 2>/dev/null && echo "Update."
cd /home/steam/ark 2>/dev/null && echo "Update.."
rm -rf /etc/arkmanager/ && echo "Update..."
rsync -a etc/arkmanager/ /etc/arkmanager/ && echo "Update...."
rm -rf etc 2>/dev/null && echo "Update..."
mkdir steamcmd 2>/dev/null && echo "Update.."
./user.sh && echo "Update.."
./run.sh && echo "Update."
